# Use postgres/example user/password credentials
version: '3.1'

services:

  database:
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - backend

  fastapi-backend:
    build: .
    env_file:
      - .env
    ports:
      - 8000:8000
    networks:
      - backend

networks:
  backend:
